#
###################################
# Site wide configuration
####################################
#
title: Alexander Stephan
email: xan@discolovers.de
description: My own personal blog
url: # the base hostname & protocol for your site
keywords: ["Technology", "Tea", "Keyboards"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Berlin
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Alexander Stephan
  avatar: avatar.png
  job: 
  bio: "Enthusiast for various things including UNIX, keyboards & tea."
  email: xan@discolovers.de
  disqus-shortname: #username
  twitter: xan_stephan #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: alexanderstephan #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: flashdance25 #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: AlexanderStephan #username
  codepen: #username
  telegram: alexanderstephan #username
  chewtv: alexanderstephan
